#!/data/data/com.termux/files/usr/bin/python
from http.server import BaseHTTPRequestHandler, HTTPServer
import time
from urllib.request import urlopen as u
from urllib.parse import unquote as uqu
from json import loads as l
from sys import argv
import os
import random

os.chdir('.'+'/'.join(argv[0].split('/')[:-1]))
q=[w.split() for w in os.popen('ifconfig').read().split('\n')]
q=[w[1].split(':')[1] for w in q if len(w) and w[0] == 'inet']
print('='*10,*enumerate(q),sep='\n')
if len(argv) > 1:
 argv1=argv[1]
 if argv1 in [w[:len(argv1)] for w in q]:
  q=[w for w in q if w[:len(argv1)] == argv1]
print('='*10,*enumerate(q),sep='\n')
if len(argv) > 2:
 port=int(argv[2])
else:
 port=9000
if len(argv) > 3:
 img='/nekopara/'+argv[3]
else:
 img='/nekopara.jpg'
if len(q) > 1:
 e=int(input())
else:
 e=0
ngrok=1
if len(argv) > 4:
 ngrok=int(argv[4])
q=q[e]
hostName = q
hostPort = port
admin=0

class MyServer(BaseHTTPRequestHandler):
 def do_GET(self):
  self.send_response(200)
  self.send_header("Content-type", "text/html; charset=utf-8")
  self.end_headers()
  self.wfile.write(bytes('''
    <h1>
    <form enctype="multipart/form-data" method="post">
     <wi><input type="file" name="u">
     <input type="submit" value="upload"></form></wi>
    </h1>
     ''','utf-8'))

 def do_POST(self):
  lenn=int(self.headers['Content-Length'])
  data=self.rfile.read(lenn)
#  open(os.popen('echo $HOME').read()[:-1]+'/0f/ddata','wb').write(data)
  print(data)
  self.send_response(200)
  self.end_headers()
  self.wfile.write(str([data]).encode())

st=1
while st:
 try:
  myServer = HTTPServer((hostName, hostPort), MyServer)
  st=0
 except:
  hostPort+=1
print(time.asctime(), "Server Starts - %s:%s" % (hostName, hostPort))

try:
    myServer.serve_forever()
except KeyboardInterrupt:
    pass

myServer.server_close()
print()
print(time.asctime(), "Server Stops - %s:%s" % (hostName, hostPort))
