#!/bin/bash
set -e
if [ $# -lt 1 ]
then
	d="*interesting commit message*"
else
	d="$1"
fi
if [ $(find . -size +51200 | grep -v "^./.git" | wc -l) -ne 0 ]
then
	echo "too large files"
	ls -l $(find . -size +51200 | grep -v "^./.git")
	exit 1
fi
git add "$(git rev-parse --show-toplevel)"
git commit -qam "$d" >/dev/null||:
git fetch -q --all
git pull -q --no-edit || :
git add "$(git rev-parse --show-toplevel)"
git commit -qam "$d" >/dev/null||:
git push -q
