%macro ddiv 1+
dsdiv %1
%endmacro

%macro wdiv 1+
wsdiv %1
%endmacro

%macro bdiv 1+
bsdiv %1
%endmacro

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

%macro dmod 1+
dsmod %1
%endmacro

%macro wmod 1+
wsmod %1
%endmacro

%macro bmod 1+
bsmod %1
%endmacro

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

%macro ddivmod 1+
dsdivmod %1
%endmacro

%macro wdivmod 1+
wsdivmod %1
%endmacro

%macro bdivmod 1+
bsdivmod %1
%endmacro

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

%macro write 1+
dswrite %1
%endmacro

%macro print 1+
dsprint %1
%endmacro

%macro put 1+
dsput %1
%endmacro

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

%macro for 1+
dsfor %1
%endmacro

%macro while 1+
dswhile %1
%endmacro

%macro if 1+
dsif %1
%endmacro

%macro elif 1+
dselif %1
%endmacro

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

