# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gera/courcerepo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gera/c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gera/c/CMakeFiles /Users/gera/c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gera/c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_test_example

# Build rule for target.
c_test_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_test_example
.PHONY : c_test_example

# fast build rule for target.
c_test_example/fast:
	$(MAKE) $(MAKESILENT) -f CLanguage/example/CMakeFiles/c_test_example.dir/build.make CLanguage/example/CMakeFiles/c_test_example.dir/build
.PHONY : c_test_example/fast

#=============================================================================
# Target rules for targets named test_any

# Build rule for target.
test_any: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_any
.PHONY : test_any

# fast build rule for target.
test_any/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/any/CMakeFiles/test_any.dir/build.make CppLanguage/any/CMakeFiles/test_any.dir/build
.PHONY : test_any/fast

#=============================================================================
# Target rules for targets named playground

# Build rule for target.
playground: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 playground
.PHONY : playground

# fast build rule for target.
playground/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/playground/CMakeFiles/playground.dir/build.make CppLanguage/playground/CMakeFiles/playground.dir/build
.PHONY : playground/fast

#=============================================================================
# Target rules for targets named test_simple_cpp

# Build rule for target.
test_simple_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_simple_cpp
.PHONY : test_simple_cpp

# fast build rule for target.
test_simple_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/simple_test/CMakeFiles/test_simple_cpp.dir/build.make CppLanguage/simple_test/CMakeFiles/test_simple_cpp.dir/build
.PHONY : test_simple_cpp/fast

#=============================================================================
# Target rules for targets named test_array

# Build rule for target.
test_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_array
.PHONY : test_array

# fast build rule for target.
test_array/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/array/CMakeFiles/test_array.dir/build.make CppLanguage/array/CMakeFiles/test_array.dir/build
.PHONY : test_array/fast

#=============================================================================
# Target rules for targets named test_complex

# Build rule for target.
test_complex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_complex
.PHONY : test_complex

# fast build rule for target.
test_complex/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/complex/CMakeFiles/test_complex.dir/build.make CppLanguage/complex/CMakeFiles/test_complex.dir/build
.PHONY : test_complex/fast

#=============================================================================
# Target rules for targets named test_abs

# Build rule for target.
test_abs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_abs
.PHONY : test_abs

# fast build rule for target.
test_abs/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/complex/CMakeFiles/test_abs.dir/build.make CppLanguage/complex/CMakeFiles/test_abs.dir/build
.PHONY : test_abs/fast

#=============================================================================
# Target rules for targets named test_str

# Build rule for target.
test_str: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_str
.PHONY : test_str

# fast build rule for target.
test_str/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/str/CMakeFiles/test_str.dir/build.make CppLanguage/str/CMakeFiles/test_str.dir/build
.PHONY : test_str/fast

#=============================================================================
# Target rules for targets named test_unique_pointer

# Build rule for target.
test_unique_pointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unique_pointer
.PHONY : test_unique_pointer

# fast build rule for target.
test_unique_pointer/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/unique_pointer/CMakeFiles/test_unique_pointer.dir/build.make CppLanguage/unique_pointer/CMakeFiles/test_unique_pointer.dir/build
.PHONY : test_unique_pointer/fast

#=============================================================================
# Target rules for targets named test_shared_pointer

# Build rule for target.
test_shared_pointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shared_pointer
.PHONY : test_shared_pointer

# fast build rule for target.
test_shared_pointer/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/shared_pointer/CMakeFiles/test_shared_pointer.dir/build.make CppLanguage/shared_pointer/CMakeFiles/test_shared_pointer.dir/build
.PHONY : test_shared_pointer/fast

#=============================================================================
# Target rules for targets named test_graph

# Build rule for target.
test_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_graph
.PHONY : test_graph

# fast build rule for target.
test_graph/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/graph/CMakeFiles/test_graph.dir/build.make CppLanguage/graph/CMakeFiles/test_graph.dir/build
.PHONY : test_graph/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... c_test_example"
	@echo "... playground"
	@echo "... test_abs"
	@echo "... test_any"
	@echo "... test_array"
	@echo "... test_complex"
	@echo "... test_graph"
	@echo "... test_shared_pointer"
	@echo "... test_simple_cpp"
	@echo "... test_str"
	@echo "... test_unique_pointer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

