# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gera/courcerepo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gera/c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gera/c/CMakeFiles /Users/gera/c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gera/c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CLanguage/example/CMakeFiles/example.dir/build.make CLanguage/example/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named playground

# Build rule for target.
playground: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 playground
.PHONY : playground

# fast build rule for target.
playground/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/playground/CMakeFiles/playground.dir/build.make CppLanguage/playground/CMakeFiles/playground.dir/build
.PHONY : playground/fast

#=============================================================================
# Target rules for targets named simple_test_cpp

# Build rule for target.
simple_test_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_test_cpp
.PHONY : simple_test_cpp

# fast build rule for target.
simple_test_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/simple_test/CMakeFiles/simple_test_cpp.dir/build.make CppLanguage/simple_test/CMakeFiles/simple_test_cpp.dir/build
.PHONY : simple_test_cpp/fast

#=============================================================================
# Target rules for targets named array

# Build rule for target.
array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array
.PHONY : array

# fast build rule for target.
array/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/array/CMakeFiles/array.dir/build.make CppLanguage/array/CMakeFiles/array.dir/build
.PHONY : array/fast

#=============================================================================
# Target rules for targets named complex

# Build rule for target.
complex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 complex
.PHONY : complex

# fast build rule for target.
complex/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/complex/CMakeFiles/complex.dir/build.make CppLanguage/complex/CMakeFiles/complex.dir/build
.PHONY : complex/fast

#=============================================================================
# Target rules for targets named abs

# Build rule for target.
abs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 abs
.PHONY : abs

# fast build rule for target.
abs/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/complex/CMakeFiles/abs.dir/build.make CppLanguage/complex/CMakeFiles/abs.dir/build
.PHONY : abs/fast

#=============================================================================
# Target rules for targets named str

# Build rule for target.
str: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 str
.PHONY : str

# fast build rule for target.
str/fast:
	$(MAKE) $(MAKESILENT) -f CppLanguage/str/CMakeFiles/str.dir/build.make CppLanguage/str/CMakeFiles/str.dir/build
.PHONY : str/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... abs"
	@echo "... array"
	@echo "... complex"
	@echo "... example"
	@echo "... playground"
	@echo "... simple_test_cpp"
	@echo "... str"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

