# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gera/cpp-2022-sudo-gera/Projects

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gera/c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gera/c/CMakeFiles /home/gera/c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gera/c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bmp

# Build rule for target.
bmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bmp
.PHONY : bmp

# fast build rule for target.
bmp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/build
.PHONY : bmp/fast

alg.o: alg.cpp.o
.PHONY : alg.o

# target to build an object file
alg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/alg.cpp.o
.PHONY : alg.cpp.o

alg.i: alg.cpp.i
.PHONY : alg.i

# target to preprocess a source file
alg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/alg.cpp.i
.PHONY : alg.cpp.i

alg.s: alg.cpp.s
.PHONY : alg.s

# target to generate assembly for a file
alg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/alg.cpp.s
.PHONY : alg.cpp.s

bmp.o: bmp.cpp.o
.PHONY : bmp.o

# target to build an object file
bmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/bmp.cpp.o
.PHONY : bmp.cpp.o

bmp.i: bmp.cpp.i
.PHONY : bmp.i

# target to preprocess a source file
bmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/bmp.cpp.i
.PHONY : bmp.cpp.i

bmp.s: bmp.cpp.s
.PHONY : bmp.s

# target to generate assembly for a file
bmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/bmp.cpp.s
.PHONY : bmp.cpp.s

esh.o: esh.cpp.o
.PHONY : esh.o

# target to build an object file
esh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/esh.cpp.o
.PHONY : esh.cpp.o

esh.i: esh.cpp.i
.PHONY : esh.i

# target to preprocess a source file
esh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/esh.cpp.i
.PHONY : esh.cpp.i

esh.s: esh.cpp.s
.PHONY : esh.s

# target to generate assembly for a file
esh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/esh.cpp.s
.PHONY : esh.cpp.s

pix.o: pix.cpp.o
.PHONY : pix.o

# target to build an object file
pix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/pix.cpp.o
.PHONY : pix.cpp.o

pix.i: pix.cpp.i
.PHONY : pix.i

# target to preprocess a source file
pix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/pix.cpp.i
.PHONY : pix.cpp.i

pix.s: pix.cpp.s
.PHONY : pix.s

# target to generate assembly for a file
pix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bmp.dir/build.make CMakeFiles/bmp.dir/pix.cpp.s
.PHONY : pix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bmp"
	@echo "... alg.o"
	@echo "... alg.i"
	@echo "... alg.s"
	@echo "... bmp.o"
	@echo "... bmp.i"
	@echo "... bmp.s"
	@echo "... esh.o"
	@echo "... esh.i"
	@echo "... esh.s"
	@echo "... pix.o"
	@echo "... pix.i"
	@echo "... pix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

