hp="8080"
sp="1080"
pradd="http://192.168.49.1"
export ftp_proxy="$pradd:$hp";
export FTP_PROXY="$pradd:$hp";
export http_proxy="$pradd:$hp";
export HTTP_PROXY="$pradd:$hp";
export https_proxy="$pradd:$hp";
export HTTPS_PROXY="$pradd:$hp";
export socks_PROXY="$pradd:$sp";
export SOCKS_PROXY="$pradd:$sp";
export socks4_PROXY="$pradd:$sp";
export SOCKS4_PROXY="$pradd:$sp";
export socks5_PROXY="$pradd:$sp";
export SOCKS5_PROXY="$pradd:$sp";
export ALL_PROXY="$pradd:$hp";
