qemu-system-x86_64 -L /Applications/UTM.app/Contents/Resources/qemu              \
-S -qmp tcp:127.0.0.1:4444,server,nowait                                         \
-nodefaults -vga none                                                            \
-smp cpus=1,sockets=1,cores=1,threads=1                                          \
-machine q35,vmport=off,i8042=off                                                \
-accel tcg,tb-size=2048                                                          \
-global PIIX4_PM.disable_s3=1                                                    \
-global ICH9-LPC.disable_s3=1                                                    \
-drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-x86_64-code.fd,readonly=on \
-drive if=pflash,unit=1,file=/Users/gera/Library/Containers/com.utmapp.UTM/Data/Documents/ubuntu_x86_64.utm/Images/efi_vars.fd \
-boot menu=on                                                                    \
-m 8192                                                                          \
-device intel-hda                                                                \
-device hda-duplex                                                               \
-name ubuntu_x86_64                                                              \
-usb -device usb-tablet,bus=usb-bus.0                                            \
-device usb-mouse,bus=usb-bus.0                                                  \
-device usb-kbd,bus=usb-bus.0                                                    \
-device ich9-usb-ehci1,id=usb-controller-0                                       \
-device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on \
-device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on \
-device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on \
-chardev spicevmc,name=usbredir,id=usbredirchardev0                              \
-device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 \
-chardev spicevmc,name=usbredir,id=usbredirchardev1                              \
-device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 \
-chardev spicevmc,name=usbredir,id=usbredirchardev2                              \
-device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 \
-device ide-cd,bus=ide.0,drive=cdrom0,bootindex=0                                \
-drive if=none,media=cdrom,id=cdrom0                                             \
-device ide-hd,bus=ide.1,drive=drive0,bootindex=1                                \
-drive if=none,media=disk,id=drive0,file=/Users/gera/Library/Containers/com.utmapp.UTM/Data/Documents/ubuntu_x86_64.utm/Images/data.qcow2,discard=unmap,detect-zeroes=unmap \
-device e1000,mac=46:4B:0F:99:A4:FB,netdev=net0                                  \
-netdev vmnet-shared,id=net0                                                     \
-device virtio-serial                                                            \
-device virtserialport,chardev=vdagent,name=com.redhat.spice.0                   \
-chardev spicevmc,id=vdagent,debug=0,name=vdagent                                \
-device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 \
-chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1                 \
-uuid 324EC3E6-1C9B-4B27-AF73-3E40CA72D1C6                                       \
-rtc base=localtime                                                              \
-device virtio-rng-pci
