#!/bin/python
import os
sh=os.system
q=os.popen('ifconfig').read()
q='\n'.join([w for w in '\n'.join([w for w in q.split('\n') if 'inet' in w]).split('  ') if 'inet' in w])
print(q)
sh('~/start-ubuntu.sh < ~/gov &')
input()
sh('touch ~/ubuntu-fs/root/exv')
import time
time.sleep(3)
