# CMake generated Testfile for 
# Source directory: /Users/gera/cpp-2022-sudo-gera/Projects/tests
# Build directory: /Users/gera/c/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(same_test8_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test8.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test8_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;4;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test8_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test8.bmp" "result.bmp")
set_tests_properties(same_test8_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;5;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/trans.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_trans_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;8;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/trans.bmp" "result.bmp")
set_tests_properties(same_trans_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;9;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/greenland_grid_velo.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_greenland_grid_velo_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;12;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/greenland_grid_velo.bmp" "result.bmp")
set_tests_properties(same_greenland_grid_velo_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;13;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bf.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test32bf_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;16;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bf.bmp" "result.bmp")
set_tests_properties(same_test32bf_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;17;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32v5.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test32v5_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;20;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32v5.bmp" "result.bmp")
set_tests_properties(same_test32v5_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;21;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test32_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;24;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32.bmp" "result.bmp")
set_tests_properties(same_test32_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;25;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/snail.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_snail_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;28;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/snail.bmp" "result.bmp")
set_tests_properties(same_snail_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;29;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test24.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test24_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;32;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test24.bmp" "result.bmp")
set_tests_properties(same_test24_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;33;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/index.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_index_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;36;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/index.bmp" "result.bmp")
set_tests_properties(same_index_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;37;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/all_gray.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_all_gray_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;40;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/all_gray.bmp" "result.bmp")
set_tests_properties(same_all_gray_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;41;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/lena.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_lena_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;44;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/lena.bmp" "result.bmp")
set_tests_properties(same_lena_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;45;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/wallpaperflare.com_wallpaper.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_wallpaperflare_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;48;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/wallpaperflare.com_wallpaper.bmp" "result.bmp")
set_tests_properties(same_wallpaperflare_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;49;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test16.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test16_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;52;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test16.bmp" "result.bmp")
set_tests_properties(same_test16_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;53;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test1.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test1_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;56;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test1.bmp" "result.bmp")
set_tests_properties(same_test1_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;57;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/blackbuck.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_blackbuck_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;60;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/blackbuck.bmp" "result.bmp")
set_tests_properties(same_blackbuck_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;61;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_24.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_bmp_24_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;64;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_24.bmp" "result.bmp")
set_tests_properties(same_bmp_24_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;65;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bfv4.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test32bfv4_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;68;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bfv4.bmp" "result.bmp")
set_tests_properties(same_test32bfv4_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;69;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/dots.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_dots_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;72;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/dots.bmp" "result.bmp")
set_tests_properties(same_dots_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;73;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_08.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_bmp_08_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;76;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_08.bmp" "result.bmp")
set_tests_properties(same_bmp_08_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;77;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_create "/Users/gera/c/bmp_cli" "str" "infile" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test4.bmp" "str" "outfile" "result.bmp" "bmp" "=" "read" "[" "infile" "]" "write" "[" "bmp" "outfile" "]")
set_tests_properties(same_test4_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;80;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test4.bmp" "result.bmp")
set_tests_properties(same_test4_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;81;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
