# CMake generated Testfile for 
<<<<<<< HEAD
# Source directory: /home/gera/cpp-2022-sudo-gera/Projects/tests
# Build directory: /home/gera/c/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(same_test8_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test8.bmp" "--same" "result.bmp")
set_tests_properties(same_test8_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;2;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test8_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test8.bmp" "result.bmp")
set_tests_properties(same_test8_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;3;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/trans.bmp" "--same" "result.bmp")
set_tests_properties(same_trans_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;6;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/trans.bmp" "result.bmp")
set_tests_properties(same_trans_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;7;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/greenland_grid_velo.bmp" "--same" "result.bmp")
set_tests_properties(same_greenland_grid_velo_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;10;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/greenland_grid_velo.bmp" "result.bmp")
set_tests_properties(same_greenland_grid_velo_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;11;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bf.bmp" "--same" "result.bmp")
set_tests_properties(same_test32bf_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;14;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bf.bmp" "result.bmp")
set_tests_properties(same_test32bf_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;15;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32v5.bmp" "--same" "result.bmp")
set_tests_properties(same_test32v5_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;18;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test32v5.bmp" "result.bmp")
set_tests_properties(same_test32v5_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;19;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32.bmp" "--same" "result.bmp")
set_tests_properties(same_test32_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;22;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test32.bmp" "result.bmp")
set_tests_properties(same_test32_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;23;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/snail.bmp" "--same" "result.bmp")
set_tests_properties(same_snail_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;26;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/snail.bmp" "result.bmp")
set_tests_properties(same_snail_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;27;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test24.bmp" "--same" "result.bmp")
set_tests_properties(same_test24_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;30;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test24.bmp" "result.bmp")
set_tests_properties(same_test24_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;31;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/index.bmp" "--same" "result.bmp")
set_tests_properties(same_index_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;34;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/index.bmp" "result.bmp")
set_tests_properties(same_index_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;35;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/all_gray.bmp" "--same" "result.bmp")
set_tests_properties(same_all_gray_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;38;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/all_gray.bmp" "result.bmp")
set_tests_properties(same_all_gray_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;39;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/lena.bmp" "--same" "result.bmp")
set_tests_properties(same_lena_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;42;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/lena.bmp" "result.bmp")
set_tests_properties(same_lena_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;43;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/wallpaperflare.com_wallpaper.bmp" "--same" "result.bmp")
set_tests_properties(same_wallpaperflare_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;46;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/wallpaperflare.com_wallpaper.bmp" "result.bmp")
set_tests_properties(same_wallpaperflare_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;47;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test16.bmp" "--same" "result.bmp")
set_tests_properties(same_test16_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;50;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test16.bmp" "result.bmp")
set_tests_properties(same_test16_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;51;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test1.bmp" "--same" "result.bmp")
set_tests_properties(same_test1_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;54;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test1.bmp" "result.bmp")
set_tests_properties(same_test1_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;55;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/blackbuck.bmp" "--same" "result.bmp")
set_tests_properties(same_blackbuck_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;58;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/blackbuck.bmp" "result.bmp")
set_tests_properties(same_blackbuck_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;59;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_24.bmp" "--same" "result.bmp")
set_tests_properties(same_bmp_24_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;62;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_24.bmp" "result.bmp")
set_tests_properties(same_bmp_24_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;63;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bfv4.bmp" "--same" "result.bmp")
set_tests_properties(same_test32bfv4_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;66;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bfv4.bmp" "result.bmp")
set_tests_properties(same_test32bfv4_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;67;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/dots.bmp" "--same" "result.bmp")
set_tests_properties(same_dots_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;70;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/dots.bmp" "result.bmp")
set_tests_properties(same_dots_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;71;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_08.bmp" "--same" "result.bmp")
set_tests_properties(same_bmp_08_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;74;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_08.bmp" "result.bmp")
set_tests_properties(same_bmp_08_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;75;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/test4.bmp" "--same" "result.bmp")
set_tests_properties(same_test4_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;78;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/test4.bmp" "result.bmp")
set_tests_properties(same_test4_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;79;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_food_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--same" "result.bmp")
set_tests_properties(same_food_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;81;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_food_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/same/food.bmp" "result.bmp")
set_tests_properties(same_food_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;82;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(negative_food_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--negative" "result.bmp")
set_tests_properties(negative_food_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;84;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(negative_food_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/negative/food.bmp" "result.bmp")
set_tests_properties(negative_food_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;85;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_5000_7000_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "5000" "7000" "result.bmp")
set_tests_properties(scale_food_5000_7000_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;87;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_5000_7000_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_5000_7000.bmp" "result.bmp")
set_tests_properties(scale_food_5000_7000_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;88;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7000_5000_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "7000" "5000" "result.bmp")
set_tests_properties(scale_food_7000_5000_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;90;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7000_5000_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_7000_5000.bmp" "result.bmp")
set_tests_properties(scale_food_7000_5000_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;91;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_700_500_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "700" "500" "result.bmp")
set_tests_properties(scale_food_700_500_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;93;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_700_500_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_700_500.bmp" "result.bmp")
set_tests_properties(scale_food_700_500_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;94;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_70_50_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "70" "50" "result.bmp")
set_tests_properties(scale_food_70_50_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;96;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_70_50_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_70_50.bmp" "result.bmp")
set_tests_properties(scale_food_70_50_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;97;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7_5_create "/home/gera/c/bmp" "/home/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "7" "5" "result.bmp")
set_tests_properties(scale_food_7_5_create PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;99;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7_5_check "diff" "/home/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_7_5.bmp" "result.bmp")
set_tests_properties(scale_food_7_5_check PROPERTIES  _BACKTRACE_TRIPLES "/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;100;add_test;/home/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
=======
# Source directory: /Users/gera/cpp-2022-sudo-gera/Projects/tests
# Build directory: /Users/gera/c/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(same_test8_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test8.bmp" "--same" "result.bmp")
set_tests_properties(same_test8_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;2;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test8_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test8.bmp" "result.bmp")
set_tests_properties(same_test8_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;3;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/trans.bmp" "--same" "result.bmp")
set_tests_properties(same_trans_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;6;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_trans_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/trans.bmp" "result.bmp")
set_tests_properties(same_trans_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;7;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/greenland_grid_velo.bmp" "--same" "result.bmp")
set_tests_properties(same_greenland_grid_velo_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;10;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_greenland_grid_velo_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/greenland_grid_velo.bmp" "result.bmp")
set_tests_properties(same_greenland_grid_velo_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;11;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bf.bmp" "--same" "result.bmp")
set_tests_properties(same_test32bf_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;14;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bf_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bf.bmp" "result.bmp")
set_tests_properties(same_test32bf_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;15;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32v5.bmp" "--same" "result.bmp")
set_tests_properties(same_test32v5_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;18;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32v5_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32v5.bmp" "result.bmp")
set_tests_properties(same_test32v5_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;19;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32.bmp" "--same" "result.bmp")
set_tests_properties(same_test32_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;22;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32.bmp" "result.bmp")
set_tests_properties(same_test32_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;23;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/snail.bmp" "--same" "result.bmp")
set_tests_properties(same_snail_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;26;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_snail_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/snail.bmp" "result.bmp")
set_tests_properties(same_snail_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;27;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test24.bmp" "--same" "result.bmp")
set_tests_properties(same_test24_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;30;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test24_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test24.bmp" "result.bmp")
set_tests_properties(same_test24_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;31;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/index.bmp" "--same" "result.bmp")
set_tests_properties(same_index_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;34;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_index_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/index.bmp" "result.bmp")
set_tests_properties(same_index_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;35;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/all_gray.bmp" "--same" "result.bmp")
set_tests_properties(same_all_gray_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;38;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_all_gray_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/all_gray.bmp" "result.bmp")
set_tests_properties(same_all_gray_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;39;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/lena.bmp" "--same" "result.bmp")
set_tests_properties(same_lena_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;42;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_lena_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/lena.bmp" "result.bmp")
set_tests_properties(same_lena_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;43;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/wallpaperflare.com_wallpaper.bmp" "--same" "result.bmp")
set_tests_properties(same_wallpaperflare_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;46;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_wallpaperflare_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/wallpaperflare.com_wallpaper.bmp" "result.bmp")
set_tests_properties(same_wallpaperflare_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;47;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test16.bmp" "--same" "result.bmp")
set_tests_properties(same_test16_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;50;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test16_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test16.bmp" "result.bmp")
set_tests_properties(same_test16_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;51;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test1.bmp" "--same" "result.bmp")
set_tests_properties(same_test1_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;54;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test1_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test1.bmp" "result.bmp")
set_tests_properties(same_test1_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;55;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/blackbuck.bmp" "--same" "result.bmp")
set_tests_properties(same_blackbuck_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;58;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_blackbuck_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/blackbuck.bmp" "result.bmp")
set_tests_properties(same_blackbuck_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;59;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_24.bmp" "--same" "result.bmp")
set_tests_properties(same_bmp_24_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;62;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_24_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_24.bmp" "result.bmp")
set_tests_properties(same_bmp_24_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;63;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test32bfv4.bmp" "--same" "result.bmp")
set_tests_properties(same_test32bfv4_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;66;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test32bfv4_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test32bfv4.bmp" "result.bmp")
set_tests_properties(same_test32bfv4_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;67;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/dots.bmp" "--same" "result.bmp")
set_tests_properties(same_dots_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;70;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_dots_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/dots.bmp" "result.bmp")
set_tests_properties(same_dots_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;71;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/bmp_08.bmp" "--same" "result.bmp")
set_tests_properties(same_bmp_08_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;74;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_bmp_08_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/bmp_08.bmp" "result.bmp")
set_tests_properties(same_bmp_08_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;75;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/test4.bmp" "--same" "result.bmp")
set_tests_properties(same_test4_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;78;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_test4_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/test4.bmp" "result.bmp")
set_tests_properties(same_test4_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;79;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_food_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--same" "result.bmp")
set_tests_properties(same_food_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;81;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(same_food_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/same/food.bmp" "result.bmp")
set_tests_properties(same_food_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;82;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(negative_food_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--negative" "result.bmp")
set_tests_properties(negative_food_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;84;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(negative_food_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/negative/food.bmp" "result.bmp")
set_tests_properties(negative_food_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;85;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_5000_7000_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "5000" "7000" "result.bmp")
set_tests_properties(scale_food_5000_7000_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;87;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_5000_7000_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_5000_7000.bmp" "result.bmp")
set_tests_properties(scale_food_5000_7000_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;88;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7000_5000_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "7000" "5000" "result.bmp")
set_tests_properties(scale_food_7000_5000_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;90;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7000_5000_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_7000_5000.bmp" "result.bmp")
set_tests_properties(scale_food_7000_5000_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;91;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_700_500_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "700" "500" "result.bmp")
set_tests_properties(scale_food_700_500_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;93;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_700_500_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_700_500.bmp" "result.bmp")
set_tests_properties(scale_food_700_500_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;94;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_70_50_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "70" "50" "result.bmp")
set_tests_properties(scale_food_70_50_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;96;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_70_50_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_70_50.bmp" "result.bmp")
set_tests_properties(scale_food_70_50_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;97;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7_5_create "/Users/gera/c/bmp" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/sources/food.bmp" "--scale" "7" "5" "result.bmp")
set_tests_properties(scale_food_7_5_create PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;99;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
add_test(scale_food_7_5_check "diff" "/Users/gera/cpp-2022-sudo-gera/Projects/tests/scale/food_7_5.bmp" "result.bmp")
set_tests_properties(scale_food_7_5_check PROPERTIES  _BACKTRACE_TRIPLES "/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;100;add_test;/Users/gera/cpp-2022-sudo-gera/Projects/tests/CMakeLists.txt;0;")
>>>>>>> 13bc93bc3633e4c71d443c4647ebed0ce0ca3ecf
