[package]
name = "list_of_objects"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
double_linked_list = { path = "../double_linked_list" }
object = { path = "../object" }
types = { path = "../types" }
